Update rule messages to use full Drupal messages
mglaman/phpstan-drupal pull request #469
Opened 2022-08-15 12:32 UTC by goba

Starts resolving #468

2022-08-15 12:56 UTC, mglaman commented on src/Rules/Drupal/EntityQuery/EntityQueryHasAccessCheckRule.php
>          ];
I wanted to add a logic branch here. If Drupal < 10.0.x show deprecated message, otherwise report as an error.

2022-12-22 14:15 UTC, mglaman commented on src/Rules/Drupal/EntityQuery/EntityQueryHasAccessCheckRule.php
>          ];
This shouldn't block the merge

2022-12-22 14:16 UTC, mglaman requested changes

2022-12-22 14:16 UTC, mglaman commented on src/Rules/Drupal/EntityQuery/EntityQueryHasAccessCheckRule.php
> +                'Relying on entity queries to check access by default is deprecated in drupal:9.2.0 and an error will be thrown from drupal:10.0.0. Call \Drupal\Core\Entity\Query\QueryInterface::acce
We need to remove `See https://www.drupal.org/node/3201242`, it's added as a tip in the PHPStan error output

2022-12-22 14:19 UTC, mglaman approved these changes
fixed the link and assertions

2022-12-22 14:25 UTC, merged

2022-12-22 15:10 UTC, dpi commented
is this going to be disruptive for baselines and ignores?

2022-12-22 15:21 UTC, mglaman commented
> is this going to be disruptive for baselines and ignores?

💩I did not consider that. Yes, it's going to completely obliterate them. That's a big breaking change. I guess I should revert this and we can schedule it for a new minor or something. Or just a new policy moving forward