$serviceDefinition can also be a string
mglaman/phpstan-drupal pull request #504
Opened 2023-01-27 11:22 UTC by prudloff-insite

Fixes #477

In our case, it seems `$serviceDefinition` can be a string containing `"@Drupal\services_defaults_test\TestInjection"`.

2023-01-27 21:31 UTC, mglaman commented on src/Drupal/DrupalAutoloader.php
>                  $this->serviceMap[$serviceId] = $serviceDefinition;
Does the service map break? Do we need to convert the string to an array containing `'class'`?

2023-01-27 21:33 UTC, mglaman commented on src/Drupal/DrupalAutoloader.php
>                  $this->serviceMap[$serviceId] = $serviceDefinition;
See https://github.com/mglaman/phpstan-drupal/blob/main/src/Drupal/DrupalServiceDefinition.php#L47 

```php
public function __construct(string $id, ?string $class, bool $public = true, ?string $alias = null)
```

I think so. https://github.com/mglaman/phpstan-drupal/blob/main/src/Drupal/ServiceMap.php#L23 this assumes it's an array

```php
    public function setDrupalServices(array $drupalServices): void
    {
        self::$services = [];

        foreach ($drupalServices as $serviceId => $serviceDefinition) {
            if (isset($serviceDefinition['parent'], $drupalServices[$serviceDefinition['parent']])) {
                $serviceDefinition = $this->resolveParentDefinition($serviceDefinition['parent'], $serviceDefinition, $drupalServices);
            }

            // @todo support factories
            if (!isset($serviceDefinition['class'])) {
```

2023-01-27 21:33 UTC, mglaman requested changes
Requesting changes, I believe we need to improve `ServiceMap::setDrupalServices`

2023-01-30 09:27 UTC, prudloff-insite commented
Hum, I'm not sure I understand enough about how `ServiceMap` works to make the change you are requesting.

2023-02-01 20:45 UTC, mglaman commented
@prudloff-insite can you provide more context on the service definition? We have tests for this

```php
assertType(MyService::class, \Drupal::service(MyService::class));
```

```
  Drupal\service_map\MyService:
    class: Drupal\service_map\MyService
  GuzzleHttp\Client: '@http_client'
  Drupal\Core\Config\ConfigFactoryInterface: '@config.factory'
  Drupal\Core\Messenger\MessengerInterface: '@messenger'
  Drupal\Core\Logger\LoggerChannelFactory: '@logger.factory'
  Drupal\Core\Logger\LoggerChannelFactoryInterface: '@logger.factory'
```

I'd like to reproduce but need more info.

2023-02-02 09:36 UTC, prudloff-insite commented
Sorry, I thought I was always testing with 1.1.27 but it turns out the project I could reproduce on was still using 0.12.15...
If I update it to 1.1.27, I can't reproduce anymore.

2023-02-02 09:36 UTC, closed without merging