PR for "Replace set-output commands" #566
mglaman/phpstan-drupal pull request #567
Opened 2023-05-13 06:02 UTC by Boegie

Resolves #566

2023-05-13 06:14 UTC, Boegie commented
Looking at the output of "require phpstan-drupal" I don't see the ` "${{ steps.branch_alias.outputs.VERSION_ALIAS }} as 1.1.99"` in it.
Neither before or after this PR.

Is this a case of "If it ain't broke don't fix it"?

2023-05-16 20:13 UTC, mglaman requested changes
PR needs updating for `core_baseline` as well

2023-05-17 20:08 UTC, mglaman commented
It looks like the following:

```
COMPOSER_MEMORY_LIMIT=-1 composer require mglaman/phpstan-drupal "dev-main as 1.1.99" phpstan/extension-installer --with-all-dependencies
```

That was on a schedule, here's from the PR

```
COMPOSER_MEMORY_LIMIT=-1 composer require mglaman/phpstan-drupal "dev-05d6e8c5420c24468041d8fcdebf7f3860a47c13 as 1.1.99" phpstan/extension-installer --with-all-dependencies
```

Ensures sha is added after `dev-` for pulling in local merge

2023-05-17 20:10 UTC, mglaman approved these changes

2023-05-17 20:15 UTC, merged